---
title: 'Data Science Mindset: Tackling Impostor Syndrome'
author: jobel
date: '2020-12-22'
slug: data-science-mindset-tackling-impostor-syndrome
categories:
  - mindset
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-12-22T17:27:02+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

At what point do you get to declare "I am a data scientist"? 

How many PhD's, decades of experience or deep learning models do you need to have under your belt before you feel like a 'real' data scientist?

The truth is, data science is advancing so rapidly that it really is impossible to keep up with everything. All you have to do is take a look at [Arxiv](https://arxiv.org) to know that there is a constant stream of new research and discoveries coming in, showing no sign of slowing down and if anything, will only speed up.

So even if you get a PhD or spend 10 years mastering a few algorithms, chances are your skills will become obsolete relatively quick. **The key is to develop a thirst for knowledge, keep learning and then solve real problems with your knowledge. **

It is unrealistic to expect yourself to truly know it all. This is the unachievable. Instead, to protect your own sanity you need to learn to manage the impostor that lurks within yourself and indeed, within all of us.


## You're not alone

The first thing to emphasise is that **you are not alone.**

Impostor syndrome is felt by almost everyone, even those that you may view as experts. This is because the amount of impostor syndrome you experience can increase as your knowledge increases. As a complete beginner, you don't know what you don't know but as an expert you become more and more aware of all the things you don't know.

The only thing that sets successful data scientists apart from everyone else is their grit and determination to carry on learning and taking action no matter how much imposter syndrome they feel. 

Social media and the internet as a whole allows people to only show their best moments, their greatest ideas, or their most polished projects. So take what you see with a pinch of salt and remember that we all go through feelings of imposter syndrome and self doubt. **What's important is the action you take despite these feelings.**


## Celebrate your wins

Data science is a complex, multi-faceted field with many areas to specialise in which can be further broken down into each of the domains that their techniques are applied to. The enumerations are endless. 

Because of this, your learning is not a straight path, it is a life long journey. You will have many ups and downs but it is important to celebrate even the smallest wins along the way as your progress, step-by-step along your path.


## Avoid comparison-itus

Comparing yourself to others (especially those that have "made it", so to speak) is like catching a bug - once you've got it it can be difficult to shake. 

While comparison is a natural part of the human experience, you should not let the success of others dictate the way you see yourself. You cannot compare your first step or your 10th step to someone elses 100th step. 

Your journey is unique because it is *YOUR* journey. Nobody else can walk the same path as you and your experiences are completely unique to you. **Embrace and love where you are, celebrate others for their achievements and then take the next step on your own path.**

Writing this post today feels as much like a letter to myself as it is a message to you. Impostor syndrome will never go away, but it can be managed and it should never be allowed to hold us back from achieving our dreams.

For me, in the past I had always been hesitant to call my self "data scientist". It sounds so grand and official and I always thought I wasn't ready yet or I hadn't learned enough yet. Ultimately, there is no one standing around waiting to bestow a grand title on your name. *It is up to you.*

Heed the wise words of Brandon Rohrer on [KDnuggets](https://www.kdnuggets.com/2017/09/data-science-imposter-syndrome.html):

>"Our goal isn’t to accumulate answers, but to ask better questions. If you are asking questions and using data to find answers, YOU ARE A DATA SCIENTIST. Period"


