---
title: 'The Secret To Setting Achievable Goals For Your Data Science Project'
author: jobel
date: '2020-09-13'
slug: setting-goals
categories:
  - 'getting started'
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-09-13T11:44:10+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Have you ever been really motivated to get stuck into analysing some data so you go ahead and download a really interesting dataset and (after a bit of googling) you import the data and go to town on it - you create summary tables, visualisations, fit a model, then go back to visualisations, then back to fitting some other model, and so on and so on. And then you wonder "what's the point of all this? I don't even know what I'm doing here". 

Well, I've been there (more than once) and the number 1 thing that I have found to combat this never-ending feeling of analysis-to-nowhere is to set actionable, achievable goals before I start any analysis. 

You need to get clear on what you're going to do, why you're doing it, how you're going to do it, what success looks like at the end and when it needs to be done by.

Keep reading on below because I will show you how to do this using the SMART goals framework within the context of a data science project.

This is the SMART goals framework:

- **Specific**: be clear on your what's and how's
- **Measurable**: identify the metrics that define success
- **Achievable**: make it challenging but still be reachable
- **Relevant**: it should be important or interesting to you
- **Time-bound**: give it a deadline

## Specific

Your goal should be clear and easy to understand. You (and your team) should be aligned with what it is you're going to do and what’s required to achieve it. 

Try to answer the following questions when making your goal specific:

- What do I want to accomplish with this project? Is it to just learn something new or will I explore and visualise my data, or fit a model and make predictions (or all of the above)?  Be specific on each of the things you're going to be doing along the way with your project.
- How will I accomplish it? What programming language will I use and what packages and functions will I be using within my chosen language?
- If this involves a team then who will need to be involved in the project with me?

## Measurable

A measurable goal identifies a metric with a specific target to show that you’ve succeeded. Consider these points during this process:

- If you're just learning something new then try to choose a metric that will indicate when you have successfully learnt the topic
- For projects that involve exploration and\or visualisation then you'll need to decide at what point you'll stop exploring.
- If you chose to fit a model and make predictions then you'll need to choose a metric that indicates good model fit or accuracy

In some cases, the statement of the goal as a whole is measurable. In other cases, you’ll need to get a little creative about what you will use to measure your success.

## Achievable

The goal should be achievable based on your current skills, knowledge and resources. This, however, doesn’t mean it should be easy. The goal should still challenge you, but not so much that you are setting yourself up for failure. The goal should help you grow and improve, and if it does fail, then at least you should "fail fast and fail forward" (Will Smith). 

Ask yourself these questions:

- Do I have the skills and knowledge necessary to achieve the goal? If not, then determine what you need to learn first and come back to this project at a later stage.
- Do I have the resources necessary to achieve the goal?
- Does the goal challenge me to improve and grow, even if I fail?

## Relevant

In this step, you must evaluate the importance of the goal. Think about whether it aligns to to your own interests as well as whether it will actually allow you to grow and move forward. 

Answering the following questions should help you through this process.

- Is it worth the time and effort? Do these goals excite and motivate me to go forward with the project?
- Is this the right time to tackle the goal? In other words, do I need to wait until I have acquired more skills and knowledge first or are there other projects and goals that make more sense right now

## Time-Bound

Your goal should have a deadline. This creates a sense of urgency in achieving the goal. A time-bound goal creates a positive tension that keeps you moving and builds the momentum you need to achieve the goal.

Depending on the size of your project, you may need to break the goal down into smaller objectives and tasks so that you continue to build momentum as you progress through the project.

If your goal uses multiple different methods, packages, and functions then it is a good idea to split these up into multiple goals that share some similar characteristics such as being achievable and relevant but might have different deadlines and metrics that define their success.

Each project is unique and there is no right or wrong goal. 

It all depends on what you want to achieve.

{{<subscribe>}}
